name: Add-ons test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '25 08 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  add-ons-test:
    strategy:
      fail-fast: false
      matrix:
        ddev_version: [ stable, HEAD ]
        add_on:
          - ddev/ddev-redis-commander
          - ddev/ddev-mongo
          - ddev/ddev-adminer
          - ddev/ddev-redis
          - ddev/ddev-solr
          - ddev/ddev-sqlsrv
          - ddev/ddev-pdfreactor
          - ddev/ddev-memcached
          - ddev/ddev-cron
          - ddev/ddev-elasticsearch

    name: Add-on test
    runs-on: ubuntu-latest

    steps:

      - name: Clone current repository
        uses: actions/checkout@v3

      - name: Retrieve last tag of add-on
        run: |
          echo "ADD_ON_LAST_TAG=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/${{ matrix.add_on }}/releases/latest | grep -oP "\/tag\/\K(.*)$")" >> $GITHUB_ENV 

      - name: Run add-on test (${{ matrix.ddev_version }})
        uses: ./
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          addon_repository: ${{ matrix.add_on }}
          addon_ref: ${{ env.ADD_ON_LAST_TAG }}
          addon_path: tested-addon
          keepalive: false
