name: Add-on simple tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '25 08 * * *'
  workflow_dispatch:

permissions:
  contents: write


jobs:
  add-on-simple-test:
    strategy:
      fail-fast: false
      matrix:
        ddev_version: [ stable, HEAD ]

    name: Add-on simple tests
    runs-on: ubuntu-latest

    steps:

      - name: Clone current repository
        uses: actions/checkout@v3

      - name: Run DDEV test (${{ matrix.ddev_version }})
        uses: ./
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          addon_repository: "ddev/ddev-redis-commander"
          addon_ref: v1.1.0
          addon_path: tested-addon
          keepalive: false

      # keepalive-workflow adds a dummy commit if there's no other action here, keeps
      # GitHub from turning off tests after 60 days
      - name: Keep alive
        uses: gautamkrishnar/keepalive-workflow@v1
        if: matrix.ddev_version == 'stable'
        with:
          commit_message: "chore(*): Automated commit to keep the repository active"
          time_elapsed: 55
