name: Disable checkout test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '25 08 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  disable-checkout-test:

    name: Disable checkout test
    runs-on: ubuntu-latest

    env:
      ADD_ON: JanoPL/ddev-kibana
      ADD_ON_REF: v1.5.0
      DDEV_VERSION: stable

    steps:

      - name: Clone current repository
        uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ADD_ON }}
          ref: ${{ env.ADD_ON_REF }}
          path: tested-addon
          submodules: 'true'

      - name: Run add-on test
        uses: ./
        with:
          ddev_version: ${{ env.DDEV_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          addon_repository: ${{ env.ADD_ON }}
          addon_ref: ${{ env.ADD_ON_REF }}
          addon_path: tested-addon
          keepalive: false
          disable_checkout_action: true

